language: cpp
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
script:
  - rm build/CMakeCache.txt
  - cmake -E make_directory /home/travis/build/ShenMian/Clementine
  - cd build
  - cmake .
  - cmake --build .
