language: cpp

compiler:
  - gcc
  - clang

os:
  - linux
  - windows
  - osx

arch:
  - amd64
  - arm64
  - ppc64le
  - s390x

script:
  - rm -rf build
  - mkdir build
  - cd build
  - cmake ../
  - cmake --build .
