language: cpp
compiler:
  - gcc
  - clang
include:
  - os: linux
    arch: amd64
  - os: linux
    arch: arm64
  - os: linux
    arch: ppc64le
  - os: linux
    arch: s390x
  - os: osx
  - os: windows
script:
  - cd build
  - rm CMakeCache.txt
  - cmake ../
  - cmake --build .
